baseurl                 = "https://le-bananafish.github.io/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "bananafish"
theme                   = "sam"
googleAnalytics         = "G-RFETXCY0Q9"             # Tracking code, eg. "UA-111111111-1"

# build options
buildDrafts             = false # builds drafts
enableEmoji             = true # enables the use of emoji codes
publishDir              = "sebastianlau"

[markup]
    [markup.goldmark] # markdown
        [markup.goldmark.renderer]
            unsafe      = true # allows HTML tags in markdown
    [markup.highlight] # code highlighting
        codeFences      = true
        lineNos         = true
        style           = "nord" # https://pygments.org/styles/

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 NZST"
    favicon             = "/sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Copyright 2018 Sebastian Lau.<p><a href='https://gohugo.io'>Hugo</a> with <a href='https://github.com/victoriadrake/hugo-theme-sam'>Sam theme</a>.</p>"
    fontFamily          = "Outfit"
    fontWeightDefault   = "100"
    # Separate font weights with ;
    fontWeights         = "100;300"
    # codeFamily          = ""
    showTagsInLists     = false
    # displays post data (date, tags, word count) in <header> if true, in <main> if false
    displayHeader       = true
    # maxWidth            = "600x"

# Metadata
    description         = "Thoughts, ideas and boredom."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

    RelativeURLs=true
    CanonifyURLs=true

[[params.mainMenu]]
    link = "/posts"
    text = "thoughts"

# [[params.mainMenu]]
#     link = "/gallery"
#     text = "gallery"

# [[params.mainMenu]]
#     link = "/tags/stories"
#     text = "stories"

# [[params.mainMenu]]
#     link = "/tags/archive"
#     text = "archive"

[[params.mainMenu]]
    link = "/extras"
    text = "extras"

[[params.mainMenu]]
    link = "/about"
    text = "who is this random?"

# [[params.mainMenu]]
    # link = "/links"
    # text = "links"
